In [6]:
import pandas as pd 

df = pd.read_csv('../data/2019-2024_combined_stats.csv')

print(df.head())
print(df.columns)
df.head()

    Rk                 Player   Age Team Pos     G    GS    MP    FG   FGA  \
0  1.0           James Harden  30.0  HOU  SG  68.0  68.0  36.5   9.9  22.3
1  2.0           Bradley Beal  26.0  WAS  SG  57.0  57.0  36.0  10.4  22.9
2  3.0         Damian Lillard  29.0  POR  PG  66.0  66.0  37.5   9.5  20.4
3  4.0             Trae Young  21.0  ATL  PG  60.0  60.0  35.3   9.1  20.8
4  5.0  Giannis Antetokounmpo  25.0  MIL  PF  63.0  63.0  30.4  10.9  19.7

   ...   DRB   TRB  AST  STL  BLK  TOV   PF   PTS                 Awards  \
0  ...   5.5   6.6  7.5  1.8  0.9  4.5  3.3  34.3            MVP-3ASNBA1
1  ...   3.3   4.2  6.1  1.2  0.4  3.4  2.2  30.5                    NaN
2  ...   3.8   4.3  8.0  1.1  0.3  2.9  1.7  30.0            MVP-8ASNBA2
3  ...   3.7   4.3  9.3  1.1  0.1  4.8  1.7  29.6                     AS
4  ...  11.4  13.6  5.6  1.0  1.0  3.7  3.1  29.5  MVP-1DPOY-1ASNBA1DEF1

   Player-additional
0          hardeja01
1           bealbr01
2          lillada01
3          youngtr01
4          antetgi01

[5 rows x 32 columns]
Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Awards', 'Player-additional'],
      dtype='object')

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Player-additional
0,1.0,James Harden,30.0,HOU,SG,68.0,68.0,36.5,9.9,22.3,...,5.5,6.6,7.5,1.8,0.9,4.5,3.3,34.3,MVP-3ASNBA1,hardeja01
1,2.0,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,...,3.3,4.2,6.1,1.2,0.4,3.4,2.2,30.5,NaN,bealbr01
2,3.0,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,...,3.8,4.3,8.0,1.1,0.3,2.9,1.7,30.0,MVP-8ASNBA2,lillada01
3,4.0,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,...,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6,AS,youngtr01
4,5.0,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,...,11.4,13.6,5.6,1.0,1.0,3.7,3.1,29.5,MVP-1DPOY-1ASNBA1DEF1,antetgi01

In [ ]:
# drop columns that aren't needed
df = df.drop(columns=["Rk", "Awards"], errors='ignore')
df.head()

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Player-additional
0,James Harden,30.0,HOU,SG,68.0,68.0,36.5,9.9,22.3,0.444,...,1.0,5.5,6.6,7.5,1.8,0.9,4.5,3.3,34.3,hardeja01
1,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,0.455,...,0.9,3.3,4.2,6.1,1.2,0.4,3.4,2.2,30.5,bealbr01
2,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,0.463,...,0.5,3.8,4.3,8.0,1.1,0.3,2.9,1.7,30.0,lillada01
3,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,0.437,...,0.5,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6,youngtr01
4,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,0.553,...,2.2,11.4,13.6,5.6,1.0,1.0,3.7,3.1,29.5,antetgi01

In [8]:
# handle missing values for percentages
for col in ["FG%", "3P%", "2P%", "eFG%", "FT%"]:
    if col in df.columns:
        df[col] = df[col].fillna(0)

# handle missing values for everything else
df = df.fillna(0)

df.isnull().sum().sum()

0

In [9]:
df["Player"].value_counts().head(10)

Player
Spencer Dinwiddie    11
Daniel Theis         11
Andre Drummond       11
Robert Covington     11
Luke Kornet          10
Wenyen Gabriel       10
Damian Jones         10
Mike Muscala         10
Darius Bazley         9
Josh Richardson       9
Name: count, dtype: int64

In [10]:
df.info()
df.describe().T.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3587 entries, 0 to 3586
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             3587 non-null   object
 1   Age                3587 non-null   float64
 2   Team               3587 non-null   object
 3   Pos                3587 non-null   object
 4   G                  3587 non-null   float64
 5   GS                 3587 non-null   float64
 6   MP                 3587 non-null   float64
 7   FG                 3587 non-null   float64
 8   FGA                3587 non-null   float64
 9   FG%                3587 non-null   float64
 10  3P                 3587 non-null   float64
 11  3PA                3587 non-null   float64
 12  3P%                3587 non-null   float64
 13  2P                 3587 non-null   float64
 14  2PA                3587 non-null   float64
 15  2P%                3587 non-null   float64
 16  eFG%               3587 non-null   float64
 17  FT                 3587 non-null   float64
 18  FTA                3587 non-null   float64
 19  FT%                3587 non-null   float64
 20  ORB                3587 non-null   float64
 21  DRB                3587 non-null   float64
 22  TRB                3587 non-null   float64
 23  AST                3587 non-null   float64
 24  STL                3587 non-null   float64
 25  BLK                3587 non-null   float64
 26  TOV                3587 non-null   float64
 27  PF                 3587 non-null   float64
 28  PTS                3587 non-null   float64
 29  Player-additional  3587 non-null   object
dtypes: float64(26), object(4)
memory usage: 840.8+ KB

      count       mean        std  min   25%   50%   75%   max
Age  3587.0  25.944243   4.284984  0.0  23.0  25.0  29.0  43.0
G    3587.0  39.169780  24.365808  0.0  17.0  40.0  61.0  84.0
GS   3587.0  17.864511  23.908744  0.0   0.0   5.0  29.0  83.0
MP   3587.0  18.862559   9.452759  0.0  11.4  18.2  26.7  43.5
FG   3587.0   3.058377   2.292885  0.0   1.3   2.5   4.2  11.5

In [11]:
# data cleaning

# there is no season column, but we can use the age column to sort by season
df = df.sort_values(by=["Player", "Age"]).reset_index(drop=True)

# Create next season targets
# only do points, rebounds, assists, steals, blocks, turnovers, 3P, FG%, FT%
target_cols = ["PTS", "TRB", "AST", "STL", "BLK", "TOV", "3P", "FG%", "FT%"]

for col in target_cols:
    df[f"{col}_next"] = df.groupby("Player")[col].shift(-1)

# drop rows where the next season's stats are missing (so no following season)
next_cols = [f"{c}_next" for c in target_cols]
df_model = df.dropna(subset=next_cols).copy()

df_model.shape, df_model[next_cols].head()

# inputs (current season stats)
feature_cols = [
    "Age", "G", "MP", "FGA", "3PA", "FTA", "FG", "3P", "FT", "TRB", "AST", "STL", "BLK",
    "TOV", "PTS", "FG%", "FT%",
]

# keep columns that actually exist
feature_cols = [c for c in feature_cols if c in df_model.columns]

X = df_model[feature_cols].copy()
Y = df_model[[f"{c}_next" for c in target_cols]].copy()

X.head(), Y.head()

(    Age     G    MP  FGA  3PA  FTA   FG   3P   FT  TRB  AST  STL  BLK  TOV  \
 0  23.0  35.0   9.9  3.6  3.0  0.1  1.5  1.3  0.1  1.3  0.6  0.2  0.0  0.3
 2  22.0  15.0   7.2  2.9  1.7  0.5  1.5  0.7  0.1  1.4  0.1  0.1  0.0  0.2
 3  22.0   1.0   2.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 4  22.0  14.0   7.6  3.1  1.8  0.6  1.5  0.7  0.1  1.4  0.1  0.1  0.0  0.2
 6  19.0  72.0  19.5  7.4  3.6  0.7  3.4  1.4  0.6  2.1  1.0  0.6  0.2  0.6

    PTS    FG%    FT%
 0  4.4  0.424  1.000
 2  3.7  0.500  0.250
 3  2.0  1.000  0.000
 4  3.9  0.488  0.250
 6  8.9  0.465  0.894  ,
    PTS_next  TRB_next  AST_next  STL_next  BLK_next  TOV_next  3P_next  \
 0       4.5       1.1       0.5       0.2       0.1       0.2      1.2
 2       2.0       1.0       0.0       0.0       0.0       0.0      0.0
 3       3.9       1.4       0.1       0.1       0.0       0.2      0.7
 4       3.2       1.2       0.5       0.2       0.1       0.3      0.3
 6       2.4       0.9       0.3       0.1       0.1       0.4      0.5

    FG%_next  FT%_next
 0     0.423     0.895
 2     1.000     0.000
 3     0.488     0.250
 4     0.446     0.652
 6     0.290     1.000  )

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

# train/test split
# use last season (23-24) as test set, earlier seasons as train 
# all but oldest seasons
train = df_model[df_model["Age"] < df_model["Age"].max()]
# last age is last season which is test
test = df_model[df_model["Age"] == df_model["Age"].max()]

X_train, Y_train = train[feature_cols], train[[f"{c}_next" for c in target_cols]]
X_test, Y_test = test[feature_cols], test[[f"{c}_next" for c in target_cols]]

# choose model
rf = RandomForestRegressor(n_estimators=200, random_state=42)

# wrap for multi-output
model = MultiOutputRegressor(rf)

# train
model.fit(X_train, Y_train)

MultiOutputRegressor(estimator=RandomForestRegressor(n_estimators=200,
                                                     random_state=42))

In [ ]:
from sklearn.metrics import mean_absolute_error

# evaluating model performance
Y_pred = model.predict(X_test)

mae_scores = {}