In [2]:
import pandas as pd 

df = pd.read_csv('../data/2019-2024_combined_stats.csv')

print(df.head())
print(df.columns)
df.head()

    Rk                 Player   Age Team Pos     G    GS    MP    FG   FGA  \
0  1.0           James Harden  30.0  HOU  SG  68.0  68.0  36.5   9.9  22.3
1  2.0           Bradley Beal  26.0  WAS  SG  57.0  57.0  36.0  10.4  22.9
2  3.0         Damian Lillard  29.0  POR  PG  66.0  66.0  37.5   9.5  20.4
3  4.0             Trae Young  21.0  ATL  PG  60.0  60.0  35.3   9.1  20.8
4  5.0  Giannis Antetokounmpo  25.0  MIL  PF  63.0  63.0  30.4  10.9  19.7

   ...   DRB   TRB  AST  STL  BLK  TOV   PF   PTS                 Awards  \
0  ...   5.5   6.6  7.5  1.8  0.9  4.5  3.3  34.3            MVP-3ASNBA1
1  ...   3.3   4.2  6.1  1.2  0.4  3.4  2.2  30.5                    NaN
2  ...   3.8   4.3  8.0  1.1  0.3  2.9  1.7  30.0            MVP-8ASNBA2
3  ...   3.7   4.3  9.3  1.1  0.1  4.8  1.7  29.6                     AS
4  ...  11.4  13.6  5.6  1.0  1.0  3.7  3.1  29.5  MVP-1DPOY-1ASNBA1DEF1

   Player-additional
0          hardeja01
1           bealbr01
2          lillada01
3          youngtr01
4          antetgi01

[5 rows x 32 columns]
Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Awards', 'Player-additional'],
      dtype='object')

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Player-additional
0,1.0,James Harden,30.0,HOU,SG,68.0,68.0,36.5,9.9,22.3,...,5.5,6.6,7.5,1.8,0.9,4.5,3.3,34.3,MVP-3ASNBA1,hardeja01
1,2.0,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,...,3.3,4.2,6.1,1.2,0.4,3.4,2.2,30.5,NaN,bealbr01
2,3.0,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,...,3.8,4.3,8.0,1.1,0.3,2.9,1.7,30.0,MVP-8ASNBA2,lillada01
3,4.0,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,...,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6,AS,youngtr01
4,5.0,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,...,11.4,13.6,5.6,1.0,1.0,3.7,3.1,29.5,MVP-1DPOY-1ASNBA1DEF1,antetgi01

In [3]:
# drop columns that aren't needed
df = df.drop(columns=["Rk", "Awards"], errors='ignore')
df.head()

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Player-additional
0,James Harden,30.0,HOU,SG,68.0,68.0,36.5,9.9,22.3,0.444,...,1.0,5.5,6.6,7.5,1.8,0.9,4.5,3.3,34.3,hardeja01
1,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,0.455,...,0.9,3.3,4.2,6.1,1.2,0.4,3.4,2.2,30.5,bealbr01
2,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,0.463,...,0.5,3.8,4.3,8.0,1.1,0.3,2.9,1.7,30.0,lillada01
3,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,0.437,...,0.5,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6,youngtr01
4,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,0.553,...,2.2,11.4,13.6,5.6,1.0,1.0,3.7,3.1,29.5,antetgi01

In [4]:
# handle missing values for percentages
for col in ["FG%", "3P%", "2P%", "eFG%", "FT%"]:
    if col in df.columns:
        df[col] = df[col].fillna(0)

# handle missing values for everything else
df = df.fillna(0)

df.isnull().sum().sum()

0

In [5]:
df["Player"].value_counts().head(10)

Player
Spencer Dinwiddie    11
Daniel Theis         11
Andre Drummond       11
Robert Covington     11
Luke Kornet          10
Wenyen Gabriel       10
Damian Jones         10
Mike Muscala         10
Darius Bazley         9
Josh Richardson       9
Name: count, dtype: int64

In [6]:
df.info()
df.describe().T.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3587 entries, 0 to 3586
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             3587 non-null   object
 1   Age                3587 non-null   float64
 2   Team               3587 non-null   object
 3   Pos                3587 non-null   object
 4   G                  3587 non-null   float64
 5   GS                 3587 non-null   float64
 6   MP                 3587 non-null   float64
 7   FG                 3587 non-null   float64
 8   FGA                3587 non-null   float64
 9   FG%                3587 non-null   float64
 10  3P                 3587 non-null   float64
 11  3PA                3587 non-null   float64
 12  3P%                3587 non-null   float64
 13  2P                 3587 non-null   float64
 14  2PA                3587 non-null   float64
 15  2P%                3587 non-null   float64
 16  eFG%               3587 non-null   float64
 17  FT                 3587 non-null   float64
 18  FTA                3587 non-null   float64
 19  FT%                3587 non-null   float64
 20  ORB                3587 non-null   float64
 21  DRB                3587 non-null   float64
 22  TRB                3587 non-null   float64
 23  AST                3587 non-null   float64
 24  STL                3587 non-null   float64
 25  BLK                3587 non-null   float64
 26  TOV                3587 non-null   float64
 27  PF                 3587 non-null   float64
 28  PTS                3587 non-null   float64
 29  Player-additional  3587 non-null   object
dtypes: float64(26), object(4)
memory usage: 840.8+ KB

      count       mean        std  min   25%   50%   75%   max
Age  3587.0  25.944243   4.284984  0.0  23.0  25.0  29.0  43.0
G    3587.0  39.169780  24.365808  0.0  17.0  40.0  61.0  84.0
GS   3587.0  17.864511  23.908744  0.0   0.0   5.0  29.0  83.0
MP   3587.0  18.862559   9.452759  0.0  11.4  18.2  26.7  43.5
FG   3587.0   3.058377   2.292885  0.0   1.3   2.5   4.2  11.5

In [7]:
# data cleaning

# there is no season column, but we can use the age column to sort by season
df = df.sort_values(by=["Player", "Age"]).reset_index(drop=True)

# Create next season targets
# only do points, rebounds, assists, steals, blocks, turnovers, 3P, FG%, FT%
target_cols = ["PTS", "TRB", "AST", "STL", "BLK", "TOV", "3P", "FG%", "FT%"]

for col in target_cols:
    df[f"{col}_next"] = df.groupby("Player")[col].shift(-1)

# drop rows where the next season's stats are missing (so no following season)
next_cols = [f"{c}_next" for c in target_cols]
df_model = df.dropna(subset=next_cols).copy()

df_model.shape, df_model[next_cols].head()

# inputs (current season stats)
feature_cols = [
    "Age", "G", "MP", "FGA", "3PA", "FTA", "FG", "3P", "FT", "TRB", "AST", "STL", "BLK",
    "TOV", "PTS", "FG%", "FT%",
]

# keep columns that actually exist
feature_cols = [c for c in feature_cols if c in df_model.columns]

X = df_model[feature_cols].copy()
Y = df_model[[f"{c}_next" for c in target_cols]].copy()

X.head(), Y.head()

(    Age     G    MP  FGA  3PA  FTA   FG   3P   FT  TRB  AST  STL  BLK  TOV  \
 0  23.0  35.0   9.9  3.6  3.0  0.1  1.5  1.3  0.1  1.3  0.6  0.2  0.0  0.3
 2  22.0  15.0   7.2  2.9  1.7  0.5  1.5  0.7  0.1  1.4  0.1  0.1  0.0  0.2
 3  22.0   1.0   2.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 4  22.0  14.0   7.6  3.1  1.8  0.6  1.5  0.7  0.1  1.4  0.1  0.1  0.0  0.2
 6  19.0  72.0  19.5  7.4  3.6  0.7  3.4  1.4  0.6  2.1  1.0  0.6  0.2  0.6

    PTS    FG%    FT%
 0  4.4  0.424  1.000
 2  3.7  0.500  0.250
 3  2.0  1.000  0.000
 4  3.9  0.488  0.250
 6  8.9  0.465  0.894  ,
    PTS_next  TRB_next  AST_next  STL_next  BLK_next  TOV_next  3P_next  \
 0       4.5       1.1       0.5       0.2       0.1       0.2      1.2
 2       2.0       1.0       0.0       0.0       0.0       0.0      0.0
 3       3.9       1.4       0.1       0.1       0.0       0.2      0.7
 4       3.2       1.2       0.5       0.2       0.1       0.3      0.3
 6       2.4       0.9       0.3       0.1       0.1       0.4      0.5

    FG%_next  FT%_next
 0     0.423     0.895
 2     1.000     0.000
 3     0.488     0.250
 4     0.446     0.652
 6     0.290     1.000  )

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

# train/test split
# use last season (23-24) as test set, earlier seasons as train 
# all but oldest seasons
train = df_model[df_model["Age"] < df_model["Age"].max()]
# last age is last season which is test
test = df_model[df_model["Age"] == df_model["Age"].max()]

X_train, Y_train = train[feature_cols], train[[f"{c}_next" for c in target_cols]]
X_test, Y_test = test[feature_cols], test[[f"{c}_next" for c in target_cols]]

# choose model
rf = RandomForestRegressor(n_estimators=200, random_state=42)

# wrap for multi-output
model = MultiOutputRegressor(rf)

# train
model.fit(X_train, Y_train)

MultiOutputRegressor(estimator=RandomForestRegressor(n_estimators=200,
                                                     random_state=42))

In [9]:
from sklearn.metrics import mean_absolute_error

# evaluating model performance
Y_pred = model.predict(X_test)

# evaluate each stat separately
mae_scores = {}
for i, col in enumerate(Y_test.columns):
    mae = mean_absolute_error(Y_test.iloc[:, i], Y_pred[:, i])
    mae_scores[col] = mae

mae_scores

{'PTS_next': 0.20599999999999996,
 'TRB_next': 0.6104999999999996,
 'AST_next': 0.5534999999999998,
 'STL_next': 0.11600000000000008,
 'BLK_next': 0.06849999999999978,
 'TOV_next': 0.30500000000000005,
 '3P_next': 0.1719999999999998,
 'FG%_next': 0.07686000000000026,
 'FT%_next': 0.19651500000000022}

In [10]:
# compare actual vs predicted for a few players to see how well the model is doing
results = X_test.copy()
results["Player"] = test["Player"].values
for i, col in enumerate(Y_test.columns):
    results[f"{col}_actual"] = Y_test.iloc[:, i].values
    results[f"{col}_pred"]= Y_pred[:, i]

print(results)

       Age     G   MP  FGA  3PA  FTA   FG   3P   FT  TRB  ...  \
3444  41.0  13.0  6.4  2.4  0.3  0.2  1.1  0.1  0.2  1.9  ...

      BLK_next_actual  BLK_next_pred  TOV_next_actual  TOV_next_pred  \
3444              0.3         0.2315              0.1          0.405

      3P_next_actual  3P_next_pred  FG%_next_actual FG%_next_pred  \
3444             0.4         0.228            0.345       0.42186

      FT%_next_actual  FT%_next_pred
3444              0.8       0.603485

[1 rows x 36 columns]

In [11]:
# model only returns oldest player so need to create a season column
# we can do this by sorting each player's seasons by age and then assigning the year
# first we need to further clean the data, players show up multiple times in one season if they got traded

import numpy as np
import pandas as pd

df = df.copy()

df = df.sort_values(["Player", "Age"]).reset_index(drop=True)

# helpers
AGG_TEAM_TOKENS = {"TOT", "2TM", "3TM", "4TM"}

# columns we will sum up
sum_cols = ["G", "GS"]
sum_cols = [c for c in sum_cols if c in df.columns]

# numeric columns to games-weight-average (most per-game stats)
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
exclude_from_weight_avg = set(sum_cols + ["Age"])
weight_avg_cols = [c for c in num_cols if c not in exclude_from_weight_avg]

def collapse_player_age(group: pd.DataFrame) -> pd.DataFrame:
    """
    Collapse rows for a single (Player, Age) to one row. Returns a single-row DataFrame.
    """
    # if there's a combined row return it
    if "Team" in group.columns and group["Team"].isin(AGG_TEAM_TOKENS).any():
        row = group[group["Team"].isin(AGG_TEAM_TOKENS)].iloc[0].copy()
        return row.to_frame().T
    
    # compute games-weighted averages
    out = group.iloc[0].copy()

    # sum games and games started
    for c in sum_cols:
        out[c] = group[c].sum() if c in group.columns else np.nan

    # weight = games played ()

    # Weight = games played (fallback to equal weights if G missing or zeros)
    w = group["G"] if "G" in group.columns else pd.Series(1.0, index=group.index)
    # Avoid all-zero division
    w = w.replace(0, np.nan)
    w = w.fillna(w.mean() if np.isfinite(w.mean()) else 1.0)

    # Games-weighted average for numeric stat columns
    for c in weight_avg_cols:
        # Keep Age from first row (already handled in exclude set)
        if c in group.columns:
            out[c] = np.average(group[c].values, weights=w.values)

    # Keep a representative team label (optional)
    if "Team" in group.columns:
        out["Team"] = "MULTI"  # or group.iloc[group["G"].idxmax()]["Team"]

    return out.to_frame().T

# 3) Apply collapse on (Player, Age)
collapsed = (
    df.groupby(["Player", "Age"], as_index=False, group_keys=False)
    .apply(collapse_player_age)
    .reset_index(drop=True)
)

collapsed.shape, collapsed.head()

/var/folders/fb/4plcrnkx6nqdqp3m0lbjd5qc0000gn/T/ipykernel_33473/2481088645.py:63: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(collapse_player_age)

((2786, 39),
         Player   Age   Team Pos     G    GS    MP   FG  FGA    FG%  ...  \
 0   A.J. Green  23.0  MULTI  SG  35.0   1.0   9.9  1.5  3.6  0.424  ...
 1   A.J. Green  24.0  MULTI  SG  56.0   0.0  11.0  1.5  3.5  0.423  ...
 2  A.J. Lawson  22.0    2TM  SG  15.0   0.0   7.2  1.5  2.9    0.5  ...
 3  A.J. Lawson  23.0  MULTI  SG  42.0   0.0   7.4  1.3  2.9  0.446  ...
 4   AJ Griffin  19.0  MULTI  SF  72.0  12.0  19.5  3.4  7.4  0.465  ...

   Player-additional PTS_next TRB_next AST_next STL_next BLK_next TOV_next  \
 0         greenaj01      4.5      1.1      0.5      0.2      0.1      0.2
 1         greenaj01      NaN      NaN      NaN      NaN      NaN      NaN
 2         lawsoaj01      2.0      1.0      0.0      0.0      0.0      0.0
 3         lawsoaj01      NaN      NaN      NaN      NaN      NaN      NaN
 4         griffaj01      2.4      0.9      0.3      0.1      0.1      0.4

   3P_next FG%_next FT%_next
 0     1.2    0.423    0.895
 1     NaN      NaN      NaN
 2     0.0      1.0      0.0
 3     NaN      NaN      NaN
 4     0.5     0.29      1.0

 [5 rows x 39 columns])

In [16]:
# create a season column

collapsed = collapsed.sort_values(["Player", "Age"]).reset_index(drop=True)
collapsed["Season"] = collapsed.groupby("Player").cumcount() + 2019

# check each player + season is unique
assert not collapsed.duplicated(["Player", "Season"]).any()

df = collapsed.copy()

target_cols = ["PTS", "TRB", "AST", "STL", "BLK", "TOV", "3P", "FG%", "FT%"]

for col in target_cols:
    df[f"{col}_next"] = df.groupby("Player")[col].shift(-1)

next_cols = [f"{c}_next" for c in target_cols]
df_model = df.dropna(subset=next_cols).copy()

# Features â€” tweak as you like
feature_cols = [
    "Age", "G", "MP",
    "FGA", "3PA", "FTA",
    "FG", "3P", "FT",
    "TRB", "AST", "STL", "BLK", "TOV", "PTS",
    "FG%", "FT%",
]
feature_cols = [c for c in feature_cols if c in df_model.columns]

test_season = df_model["Season"].max()
train = df_model[df_model["Season"] < test_season]
test = df_model[df_model["Season"] == test_season]

X_train, Y_train = train[feature_cols], train[next_cols]
X_test,  Y_test  = test[feature_cols],  test[next_cols]

print(f"Train: {X_train.shape}, Test: {X_test.shape}    (test_season={test_season})")

rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,      # let trees grow; you can tune later
    random_state=42,
    n_jobs=-1
)

model = MultiOutputRegressor(rf)
model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

mae_scores = {}
for i, col in enumerate(Y_test.columns):
    mae_scores[col] = round(mean_absolute_error(Y_test.iloc[:, i], Y_pred[:, i]), 3)

pd.Series(mae_scores).sort_index()

# Helpful to keep player/season identifiers
results = test[["Player", "Season"]].copy()

# Add predictions + actuals
for i, col in enumerate(Y_test.columns):
    results[f"{col}_actual"] = Y_test.iloc[:, i].values
    results[f"{col}_pred"]   = Y_pred[:, i]

# Sort by biggest absolute PTS error as an example
results_with_err = results.copy()
results_with_err["PTS_abs_err"] = (results_with_err["PTS_next_actual"] - results_with_err["PTS_next_pred"]).abs()

results_with_err.sort_values("PTS_abs_err", ascending=False).head(15)

# Average MAE across all 9 targets
avg_mae = np.mean(list(mae_scores.values()))
print("Average MAE across targets:", round(avg_mae, 3))

# Show MAE nicely formatted
mae_df = pd.DataFrame({"MAE": pd.Series(mae_scores)}).sort_values("MAE")
mae_df

# Map index -> target name
target_by_idx = list(Y_train.columns)
target_idx = target_by_idx.index("PTS_next")  # choose a target to inspect
rf_for_pts = model.estimators_[target_idx]

fi = pd.Series(rf_for_pts.feature_importances_, index=feature_cols).sort_values(ascending=False)
fi.head(15)

Train: (1575, 17), Test: (247, 17)    (test_season=2022)
Average MAE across targets: 0.535

PTS    0.737238
FGA    0.036326
FG     0.035933
G      0.026954
Age    0.021450
MP     0.016682
FG%    0.015810
TRB    0.015401
FT%    0.014880
AST    0.013054
TOV    0.011262
FT     0.010643
STL    0.010425
FTA    0.010335
3PA    0.008912
dtype: float64

In [15]:
df_model["Season"].unique()

array([2019, 2020, 2021, 2022])